server:
  port: 9110 # \u670D\u52A1\u7AEF\u53E3

spring:
  profiles:
    active: dev # \u73AF\u5883\u8BBE\u7F6E
  datasource: # mysql\u6570\u636E\u5E93\u8FDE\u63A5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.98:3306/quick_dine_sys?serverTimezone=GMT%2B8
    username: root
    password: root
  #spring:
  jackson: #\u8FD4\u56DEjson\u7684\u5168\u5C40\u65F6\u95F4\u683C\u5F0F
    date-format: yyyy-MM-dd HH:mm:ss  #yyyy-MM-dd
    time-zone: GMT+8

#mybatis\u65E5\u5FD7
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4GFkxZbNBJS98q8AoLyC
    keysecret: RPPjRwQ42KlpGpsGHHf8EYMVnl6t2R
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: quick-dine-oss-file

#当前系统店家的名字
quick:
  storeName: 鲲鹏膳